server:
  servlet:
    encoding:
      force-response: true

spring:
  session:
    store-type: jdbc
  jpa:
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: true
  config:
    use-legacy-processing: true
  profiles:
    include: oauth
